---
# Source: task-openshift/templates/task-kn-apply.yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kn-apply
  labels:
    app.kubernetes.io/version: 0.2.1
  annotations:
    tekton.dev/source: "https://github.com/openshift-pipelines/task-openshift"
    artifacthub.io/category: integration-delivery
    artifacthub.io/maintainers: |
      - name: OpenShift Pipeline task maintainers
        email: pipelines-extcomm@redhat.com
    artifacthub.io/provider: Red Hat
    artifacthub.io/recommendations: |
      - url: https://tekton.dev/
    tekton.dev/displayName: CLI
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/tags: cli
spec:
  description: >-
    This task deploys a given image to a Knative Service.
    It uses `kn service apply` to create or update given knative service.
  
  params:
    - name: SERVICE
      description: Knative service name
    - name: IMAGE
      description: Image to deploy

  steps:
    - name: kn
      env:
        - name: HOME
          value: /tekton/home
      image: registry.redhat.io/openshift-serverless-1/client-kn-rhel8:1.11.2-4
      command: ["/ko-app/kn"]
      args:
        ["service", "apply", "$(params.SERVICE)", "--image", "$(params.IMAGE)"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
