---
name: tektoncd
description: Setup Tekton Pipeline on KinD

runs:
  using: composite
  steps:
    # "kind-action" provides a running KinD instance and configured kubectl client.
    - uses: helm/kind-action@v1.8.0
      with:
        cluster_name: kind

    # "setup-tektoncd" provides Tekton Pipeline, CLI and a local container registry.
    - uses: openshift-pipelines/setup-tektoncd@v1
      with:
        pipeline_version: latest
        feature_flags: "{}"
        cli_version: latest
        setup_registry: "true"
        patch_etc_hosts: "true"
