---
# Source: task-containers/templates/task-skopeo-copy.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-copy
  labels:
    app.kubernetes.io/version: 0.2.0
  annotations:
    tekton.dev/categories: containers
    tekton.dev/pipelines.minVersion: 0.41.0
    tekton.dev/tags: containers
spec:
  description: |
    Uses `skopeo copy` to replicate the `SOURCE` (param) container image into
    `DESTINATION`. After copying the source and destination images SHA256 digest
    is stored as results.

  params:
    - name: SOURCE
      type: string
      description: |
        Fully qualified source container image name, including tag, to be copied
        into `DESTINATION` param.
    - name: DESTINATION
      type: string
      description: |
        Fully qualified destination container image name, including tag.
    - name: TLS_VERIFY
      type: string
      default: "true"
      description: |
        Sets the TLS verification flags, `true` is recommended.
    - name: VERBOSE
      type: string
      default: "false"
      description: |
        Shows a more verbose (debug) output.

  results:
    - name: SOURCE_DIGEST
      type: string
      description: |
        Source image SHA256 digest.
    - name: DESTINATION_DIGEST
      type: string
      description: |
        Destination image SHA256 digest.

  volumes:
    - name: scripts-dir
      emptyDir: {}

  stepTemplate:
    env:
      
      - name: PARAMS_SOURCE
        value: "$(params.SOURCE)"
      - name: PARAMS_DESTINATION
        value: "$(params.DESTINATION)"
      - name: PARAMS_TLS_VERIFY
        value: "$(params.TLS_VERIFY)"
      - name: PARAMS_VERBOSE
        value: "$(params.VERBOSE)"
      - name: RESULTS_SOURCE_DIGEST_PATH
        value: "$(results.SOURCE_DIGEST.path)"
      - name: RESULTS_DESTINATION_DIGEST_PATH
        value: "$(results.DESTINATION_DIGEST.path)"

  steps:
    - name: load-scripts
      image: registry.access.redhat.com/ubi8-minimal:8.9
      workingDir: /scripts
      script: |
        set -e
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKIyB0ZWt0b24ncyBob21lIGRpcmVjdG9yeQpkZWNsYXJlIC1yeCBURUtUT05fSE9NRT0iJHtURUtUT05fSE9NRTotL3Rla3Rvbi9ob21lfSIKCiMKIyBGdW5jdGlvbnMKIwoKZnVuY3Rpb24gZmFpbCgpIHsKICAgIGVjaG8gIkVSUk9SOiAkeyp9IiAyPiYxCiAgICBleGl0IDEKfQoKZnVuY3Rpb24gcGhhc2UoKSB7CiAgICBlY2hvICItLS0+IFBoYXNlOiAkeyp9Li4uIgp9CgojIGFzc2VydCBsb2NhbCB2YXJpYWJsZXMgYXJlIGV4cG9yZXRlZCBvbiB0aGUgZW52aXJvbm1lbnQKZnVuY3Rpb24gZXhwb3J0ZWRfb3JfZmFpbCgpIHsKICAgIGRlY2xhcmUgLWEgX3JlcXVpcmVkX3ZhcnM9IiR7QH0iCgogICAgZm9yIHYgaW4gJHtfcmVxdWlyZWRfdmFyc1tAXX07IGRvCiAgICAgICAgW1sgLXogIiR7IXZ9IiBdXSAmJgogICAgICAgICAgICBmYWlsICInJHt2fScgZW52aXJvbm1lbnQgdmFyaWFibGUgaXMgbm90IHNldCEiCiAgICBkb25lCgogICAgcmV0dXJuIDAKfQo=" |base64 -d >common.sh
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKZGVjbGFyZSAtcnggUEFSQU1TX1NPVVJDRT0iJHtQQVJBTVNfU09VUkNFOi19IgpkZWNsYXJlIC1yeCBQQVJBTVNfREVTVElOQVRJT049IiR7UEFSQU1TX0RFU1RJTkFUSU9OOi19IgpkZWNsYXJlIC1yeCBQQVJBTVNfVExTX1ZFUklGWT0iJHtQQVJBTVNfVExTX1ZFUklGWTotfSIKZGVjbGFyZSAtcnggUEFSQU1TX1ZFUkJPU0U9IiR7UEFSQU1TX1ZFUkJPU0U6LX0iCgpkZWNsYXJlIC1yeCBSRVNVTFRTX1NPVVJDRV9ESUdFU1RfUEFUSD0iJHtSRVNVTFRTX1NPVVJDRV9ESUdFU1RfUEFUSDotfSIKZGVjbGFyZSAtcnggUkVTVUxUU19ERVNUSU5BVElPTl9ESUdFU1RfUEFUSD0iJHtSRVNVTFRTX0RFU1RJTkFUSU9OX0RJR0VTVF9QQVRIOi19IgoKIwojIEFzc2VydGluZyBFbnZpcm9ubWVudAojCgpleHBvcnRlZF9vcl9mYWlsIFwKICAgIFBBUkFNU19TT1VSQ0UgXAogICAgUEFSQU1TX0RFU1RJTkFUSU9OIFwKICAgIFJFU1VMVFNfU09VUkNFX0RJR0VTVF9QQVRIIFwKICAgIFJFU1VMVFNfREVTVElOQVRJT05fRElHRVNUX1BBVEgKCiMKIyBTa29wZW8gQXV0aGVudGljYXRpb24KIwoKZGVjbGFyZSAteCBSRUdJU1RSWV9BVVRIX0ZJTEU9IiIKCmRvY2tlcl9jb25maWc9IiR7SE9NRX0vLmRvY2tlci9jb25maWcuanNvbiIKaWYgW1sgLWYgIiR7ZG9ja2VyX2NvbmZpZ30iIF1dOyB0aGVuCiAgICBwaGFzZSAiU2V0dGluZyBSRUdJU1RSWV9BVVRIX0ZJTEUgdG8gJyR7ZG9ja2VyX2NvbmZpZ30nIgogICAgUkVHSVNUUllfQVVUSF9GSUxFPSR7ZG9ja2VyX2NvbmZpZ30KZmkKCiMKIyBWZXJib3NlIE91dHB1dAojCgpkZWNsYXJlIC14IFNLT1BFT19ERUJVR19GTEFHPSIiCgppZiBbWyAiJHtQQVJBTVNfVkVSQk9TRX0iID09ICJ0cnVlIiBdXTsgdGhlbgogICAgU0tPUEVPX0RFQlVHX0ZMQUc9Ii0tZGVidWciCiAgICBzZXQgLXgKZmkK" |base64 -d >skopeo-common.sh
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc2hvcHQgLXMgaW5oZXJpdF9lcnJleGl0CnNldCAtZXUgLW8gcGlwZWZhaWwKCnNvdXJjZSAiJChkaXJuYW1lICR7QkFTSF9TT1VSQ0VbMF19KS9jb21tb24uc2giCnNvdXJjZSAiJChkaXJuYW1lICR7QkFTSF9TT1VSQ0VbMF19KS9za29wZW8tY29tbW9uLnNoIgoKcGhhc2UgIkNvcHlpbmcgJyR7UEFSQU1TX1NPVVJDRX0nIGludG8gJyR7UEFSQU1TX0RFU1RJTkFUSU9OfSciCgpzZXQgLXgKZXhlYyBza29wZW8gY29weSAke1NLT1BFT19ERUJVR19GTEFHfSBcCiAgICAtLXNyYy10bHMtdmVyaWZ5PSR7UEFSQU1TX1RMU19WRVJJRll9IFwKICAgIC0tZGVzdC10bHMtdmVyaWZ5PSR7UEFSQU1TX1RMU19WRVJJRll9IFwKICAgICR7UEFSQU1TX1NPVVJDRX0gXAogICAgJHtQQVJBTVNfREVTVElOQVRJT059Cg==" |base64 -d >skopeo-copy.sh
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc2hvcHQgLXMgaW5oZXJpdF9lcnJleGl0CnNldCAtZXUgLW8gcGlwZWZhaWwKCnNvdXJjZSAiJChkaXJuYW1lICR7QkFTSF9TT1VSQ0VbMF19KS9jb21tb24uc2giCnNvdXJjZSAiJChkaXJuYW1lICR7QkFTSF9TT1VSQ0VbMF19KS9za29wZW8tY29tbW9uLnNoIgoKZnVuY3Rpb24gc2tvcGVvX2luc3BlY3QoKSB7CiAgICBza29wZW8gaW5zcGVjdCAke1NLT1BFT19ERUJVR19GTEFHfSBcCiAgICAgICAgLS10bHMtdmVyaWZ5PSR7UEFSQU1TX1RMU19WRVJJRll9IFwKICAgICAgICAtLWZvcm1hdD0ne3sgLkRpZ2VzdCB9fScgXAogICAgICAgICR7MX0KfQoKcGhhc2UgIkV4dHJhY3RpbmcgJyR7UEFSQU1TX1NPVVJDRX0nIHNvdXJjZSBpbWFnZSBkaWdlc3QiCnNvdXJjZV9kaWdlc3Q9IiQoc2tvcGVvX2luc3BlY3QgJHtQQVJBTVNfU09VUkNFfSkiCnBoYXNlICJTb3VyY2UgaW1hZ2UgZGlnZXN0ICcke3NvdXJjZV9kaWdlc3R9JyIKCnBoYXNlICJFeHRyYWN0aW5nICcke1BBUkFNU19ERVNUSU5BVElPTn0nIGRlc3RpbmF0aW9uIGltYWdlIGRpZ2VzdCIKZGVzdGluYXRpb25fZGlnZXN0PSIkKHNrb3Blb19pbnNwZWN0ICR7UEFSQU1TX0RFU1RJTkFUSU9OfSkiCnBoYXNlICJEZXN0aW5hdGlvbiBpbWFnZSBkaWdlc3QgJyR7ZGVzdGluYXRpb25fZGlnZXN0fSciCgpwcmludGYgIiVzIiAke3NvdXJjZV9kaWdlc3R9ID4ke1JFU1VMVFNfU09VUkNFX0RJR0VTVF9QQVRIfQpwcmludGYgIiVzIiAke2Rlc3RpbmF0aW9uX2RpZ2VzdH0gPiR7UkVTVUxUU19ERVNUSU5BVElPTl9ESUdFU1RfUEFUSH0K" |base64 -d >skopeo-results.sh
        chmod +x skopeo-*.sh
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts

    - name: skopeo-copy
      image: registry.access.redhat.com/ubi8/skopeo:8.9
      command:
        - /scripts/skopeo-copy.sh
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts

    - name: skopeo-results
      image: registry.access.redhat.com/ubi8/skopeo:8.9
      command:
        - /scripts/skopeo-results.sh
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
