---
# Source: task-containers/templates/task-skopeo-copy.yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: skopeo-copy
  labels:
    app.kubernetes.io/version: 0.4.1
  annotations:
    tekton.dev/source: "https://github.com/openshift-pipelines/task-containers"
    artifacthub.io/category: integration-delivery
    artifacthub.io/maintainers: |
      - name: OpenShift Pipeline task maintainers
        email: pipelines-extcomm@redhat.com
    artifacthub.io/provider: Red Hat
    artifacthub.io/recommendations: |
      - url: https://tekton.dev/
    tekton.dev/categories: containers
    tekton.dev/pipelines.minVersion: 0.41.0
    tekton.dev/tags: containers
spec:
  description: |
    Skopeo is a command line tool for working with remote image registries.
    Skopeo doesn’t require a daemon to be running while performing its operations. In particular,
    the handy skopeo command called copy will ease the whole image copy operation. 
    The copy command will take care of copying the image from internal.registry to production.registry.
    If your production registry requires credentials to login in order to push the image, skopeo can handle that as well.
    After copying the source and destination images SHA256 digest is stored as results.
  workspaces:
    - name: images_url
      optional: true
      description: |
        For storing image urls in case we have more than one image to copy.
  params:
    - name: SOURCE_IMAGE_URL
      type: string
      description: |
        Fully qualified source container image name, including tag, to be copied
        into `DESTINATION_IMAGE_URL` param.
    - name: DESTINATION_IMAGE_URL
      type: string
      description: |
        Fully qualified destination container image name, including tag.
    - name: SRC_TLS_VERIFY
      type: string
      default: "true"
      description: |
        Sets the TLS verification flags for the source registry, `true` is recommended.
    - name: DEST_TLS_VERIFY
      type: string
      default: "true"
      description: |
        Sets the TLS verification flags for the destination registry, `true` is recommended.
    - name: VERBOSE
      type: string
      default: "false"
      description: |
        Shows a more verbose (debug) output.

  results:
    - name: SOURCE_DIGEST
      type: string
      description: |
        Source image SHA256 digest.
    - name: DESTINATION_DIGEST
      type: string
      description: |
        Destination image SHA256 digest.

  volumes:
    - name: scripts-dir
      emptyDir: {}
    
  stepTemplate:
    env:
      
      - name: PARAMS_SOURCE_IMAGE_URL
        value: "$(params.SOURCE_IMAGE_URL)"
      - name: PARAMS_DESTINATION_IMAGE_URL
        value: "$(params.DESTINATION_IMAGE_URL)"
      - name: PARAMS_SRC_TLS_VERIFY
        value: "$(params.SRC_TLS_VERIFY)"
      - name: PARAMS_DEST_TLS_VERIFY
        value: "$(params.DEST_TLS_VERIFY)"
      - name: PARAMS_VERBOSE
        value: "$(params.VERBOSE)"
      - name: WORKSPACES_IMAGES_URL_BOUND
        value: "$(workspaces.images_url.bound)"
      - name: WORKSPACES_IMAGES_URL_PATH
        value: "$(workspaces.images_url.path)"
      - name: RESULTS_SOURCE_DIGEST_PATH
        value: "$(results.SOURCE_DIGEST.path)"
      - name: RESULTS_DESTINATION_DIGEST_PATH
        value: "$(results.DESTINATION_DIGEST.path)"

  steps:
    - name: skopeo-copy
      env:
        - name: HOME
          value: /workspace/home
      image: registry.access.redhat.com/ubi8/skopeo:8.10-5
      script: |
        set -e
        echo "/scripts/buildah-bud.sh"
        echo "/scripts/buildah-common.sh"
        echo "/scripts/common.sh"
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKIyB0ZWt0b24ncyBob21lIGRpcmVjdG9yeQpkZWNsYXJlIC1yeCBURUtUT05fSE9NRT0iJHtURUtUT05fSE9NRTotL3Rla3Rvbi9ob21lfSIKCiMKIyBGdW5jdGlvbnMKIwoKZnVuY3Rpb24gZmFpbCgpIHsKICAgIGVjaG8gIkVSUk9SOiAkeyp9IiAyPiYxCiAgICBleGl0IDEKfQoKZnVuY3Rpb24gcGhhc2UoKSB7CiAgICBlY2hvICItLS0+IFBoYXNlOiAkeyp9Li4uIgp9CgojIGFzc2VydCBsb2NhbCB2YXJpYWJsZXMgYXJlIGV4cG9yZXRlZCBvbiB0aGUgZW52aXJvbm1lbnQKZnVuY3Rpb24gZXhwb3J0ZWRfb3JfZmFpbCgpIHsKICAgIGRlY2xhcmUgLWEgX3JlcXVpcmVkX3ZhcnM9IiR7QH0iCgogICAgZm9yIHYgaW4gJHtfcmVxdWlyZWRfdmFyc1tAXX07IGRvCiAgICAgICAgW1sgLXogIiR7IXZ9IiBdXSAmJgogICAgICAgICAgICBmYWlsICInJHt2fScgZW52aXJvbm1lbnQgdmFyaWFibGUgaXMgbm90IHNldCEiCiAgICBkb25lCgogICAgcmV0dXJuIDAKfQo=" |base64 -d >"/scripts/common.sh"
        echo "/scripts/s2i-build.sh"
        echo "/scripts/s2i-common.sh"
        echo "/scripts/s2i-generate.sh"
        echo "/scripts/skopeo-common.sh"
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKZGVjbGFyZSAtcnggUEFSQU1TX1NPVVJDRV9JTUFHRV9VUkw9IiR7UEFSQU1TX1NPVVJDRV9JTUFHRV9VUkw6LX0iCmRlY2xhcmUgLXJ4IFBBUkFNU19ERVNUSU5BVElPTl9JTUFHRV9VUkw9IiR7UEFSQU1TX0RFU1RJTkFUSU9OX0lNQUdFX1VSTDotfSIKZGVjbGFyZSAtcnggUEFSQU1TX1NSQ19UTFNfVkVSSUZZPSIke1BBUkFNU19TUkNfVExTX1ZFUklGWTotfSIKZGVjbGFyZSAtcnggUEFSQU1TX0RFU1RfVExTX1ZFUklGWT0iJHtQQVJBTVNfREVTVF9UTFNfVkVSSUZZOi19IgpkZWNsYXJlIC1yeCBQQVJBTVNfVkVSQk9TRT0iJHtQQVJBTVNfVkVSQk9TRTotfSIKCmRlY2xhcmUgLXJ4IFdPUktTUEFDRVNfSU1BR0VTX1VSTF9QQVRIPSIke1dPUktTUEFDRVNfSU1BR0VTX1VSTF9QQVRIOi19IgpkZWNsYXJlIC1yeCBXT1JLU1BBQ0VTX0lNQUdFU19VUkxfQk9VTkQ9IiR7V09SS1NQQUNFU19JTUFHRVNfVVJMX0JPVU5EOi19IgoKZGVjbGFyZSAtcnggUkVTVUxUU19TT1VSQ0VfRElHRVNUX1BBVEg9IiR7UkVTVUxUU19TT1VSQ0VfRElHRVNUX1BBVEg6LX0iCmRlY2xhcmUgLXJ4IFJFU1VMVFNfREVTVElOQVRJT05fRElHRVNUX1BBVEg9IiR7UkVTVUxUU19ERVNUSU5BVElPTl9ESUdFU1RfUEFUSDotfSIKCiMKIyBBc3NlcnRpbmcgRW52aXJvbm1lbnQKIwoKZXhwb3J0ZWRfb3JfZmFpbCBcCiAgICBQQVJBTVNfU09VUkNFX0lNQUdFX1VSTCBcCiAgICBQQVJBTVNfREVTVElOQVRJT05fSU1BR0VfVVJMIFwKICAgIFJFU1VMVFNfU09VUkNFX0RJR0VTVF9QQVRIIFwKICAgIFJFU1VMVFNfREVTVElOQVRJT05fRElHRVNUX1BBVEgKICAgICAKCiMKIyBTa29wZW8gQXV0aGVudGljYXRpb24KIwoKZGVjbGFyZSAteCBSRUdJU1RSWV9BVVRIX0ZJTEU9IiIKCmRvY2tlcl9jb25maWc9Ii93b3Jrc3BhY2UvaG9tZS8uZG9ja2VyL2NvbmZpZy5qc29uIgppZiBbWyAtZiAiJHtkb2NrZXJfY29uZmlnfSIgXV07IHRoZW4KICAgIHBoYXNlICJTZXR0aW5nIFJFR0lTVFJZX0FVVEhfRklMRSB0byAnJHtkb2NrZXJfY29uZmlnfSciCiAgICBSRUdJU1RSWV9BVVRIX0ZJTEU9JHtkb2NrZXJfY29uZmlnfQpmaQoKIwojIFZlcmJvc2UgT3V0cHV0CiMKCmRlY2xhcmUgLXggU0tPUEVPX0RFQlVHX0ZMQUc9IiIKCmlmIFtbICIke1BBUkFNU19WRVJCT1NFfSIgPT0gInRydWUiIF1dOyB0aGVuCiAgICBTS09QRU9fREVCVUdfRkxBRz0iLS1kZWJ1ZyIKICAgIHNldCAteApmaQo=" |base64 -d >"/scripts/skopeo-common.sh"
        echo "/scripts/skopeo-copy.sh"
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc2hvcHQgLXMgaW5oZXJpdF9lcnJleGl0CnNldCAtZXUgLW8gcGlwZWZhaWwKCnNvdXJjZSAiJChkaXJuYW1lICIke0JBU0hfU09VUkNFWzBdfSIpL2NvbW1vbi5zaCIKc291cmNlICIkKGRpcm5hbWUgIiR7QkFTSF9TT1VSQ0VbMF19Iikvc2tvcGVvLWNvbW1vbi5zaCIKCiMgRW5zdXJlIHRoZSAvdGVrdG9uL2hvbWUvLmRvY2tlciBkaXJlY3RvcnkgZXhpc3RzCm1rZGlyIC1wIC93b3Jrc3BhY2UvaG9tZS8uZG9ja2VyCgpwaGFzZSAiQ29weWluZyAnJHtQQVJBTVNfU09VUkNFX0lNQUdFX1VSTH0nIGludG8gJyR7UEFSQU1TX0RFU1RJTkFUSU9OX0lNQUdFX1VSTH0nIgoKc2V0IC14CgppZiBbIC1uICIke1BBUkFNU19TT1VSQ0VfSU1BR0VfVVJMfSIgXSAmJiBbIC1uICIke1BBUkFNU19ERVNUSU5BVElPTl9JTUFHRV9VUkx9IiBdOyB0aGVuCiAgICBza29wZW8gY29weSAke1NLT1BFT19ERUJVR19GTEFHfSBcCiAgICAgICAgLS1zcmMtdGxzLXZlcmlmeT0iJHtQQVJBTVNfU1JDX1RMU19WRVJJRll9IiBcCiAgICAgICAgLS1kZXN0LXRscy12ZXJpZnk9IiR7UEFSQU1TX0RFU1RfVExTX1ZFUklGWX0iIFwKICAgICAgICAiJHtQQVJBTVNfU09VUkNFX0lNQUdFX1VSTH0iIFwKICAgICAgICAiJHtQQVJBTVNfREVTVElOQVRJT05fSU1BR0VfVVJMfSIKZWxzZQogICAgIyBGdW5jdGlvbiB0byBjb3B5IG11bHRpcGxlIGltYWdlcy4KICAgIGNvcHlpbWFnZXMoKSB7CiAgICAgICAgZmlsZW5hbWU9IiR7V09SS1NQQUNFU19JTUFHRVNfVVJMX1BBVEh9L3VybC50eHQiCiAgICAgICAgd2hpbGUgSUZTPSByZWFkIC1yIGxpbmUgfHwgWyAtbiAiJGxpbmUiIF0KICAgICAgICBkbwogICAgICAgICAgICBjbWQ9IiIKICAgICAgICAgICAgZm9yIHVybCBpbiAkbGluZQogICAgICAgICAgICBkbwogICAgICAgICAgICAgICAgY21kPSIkY21kICR1cmwiCiAgICAgICAgICAgIGRvbmUKICAgICAgICAgICAgcmVhZCAtcmEgU09VUkNFIDw8PCIke2NtZH0iCiAgICAgICAgICAgIHNrb3BlbyBjb3B5ICIke1NPVVJDRVtAXX0iIC0tc3JjLXRscy12ZXJpZnk9IiR7UEFSQU1TX1NSQ19UTFNfVkVSSUZZfSIgLS1kZXN0LXRscy12ZXJpZnk9IiR7UEFSQU1TX0RFU1RfVExTX1ZFUklGWX0iCiAgICAgICAgICAgIGVjaG8gIiRjbWQiCiAgICAgICAgZG9uZSA8ICIkZmlsZW5hbWUiCiAgICB9CgogICAgY29weWltYWdlcwpmaQo=" |base64 -d >"/scripts/skopeo-copy.sh"
        echo "/scripts/skopeo-results.sh"
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc2hvcHQgLXMgaW5oZXJpdF9lcnJleGl0CnNldCAtZXUgLW8gcGlwZWZhaWwKCnNvdXJjZSAiJChkaXJuYW1lICR7QkFTSF9TT1VSQ0VbMF19KS9jb21tb24uc2giCnNvdXJjZSAiJChkaXJuYW1lICR7QkFTSF9TT1VSQ0VbMF19KS9za29wZW8tY29tbW9uLnNoIgoKZnVuY3Rpb24gc2tvcGVvX2luc3BlY3QoKSB7CiAgICBsb2NhbCBpbWFnZT0iJDEiCiAgICBsb2NhbCB0bHNfdmVyaWZ5PSIkMiIKICAgIHNrb3BlbyBpbnNwZWN0ICR7U0tPUEVPX0RFQlVHX0ZMQUd9IFwKICAgICAgICAtLXRscy12ZXJpZnk9IiR7dGxzX3ZlcmlmeX0iIFwKICAgICAgICAtLWZvcm1hdD0ne3sgLkRpZ2VzdCB9fScgXAogICAgICAgICIke2ltYWdlfSIKfQoKcGhhc2UgIkV4dHJhY3RpbmcgJyR7UEFSQU1TX1NPVVJDRV9JTUFHRV9VUkx9JyBzb3VyY2UgaW1hZ2UgZGlnZXN0Igpzb3VyY2VfZGlnZXN0PSIkKHNrb3Blb19pbnNwZWN0ICIke1BBUkFNU19TT1VSQ0VfSU1BR0VfVVJMfSIgIiR7UEFSQU1TX1NSQ19UTFNfVkVSSUZZfSIpIgpwaGFzZSAiU291cmNlIGltYWdlIGRpZ2VzdCAnJHtzb3VyY2VfZGlnZXN0fSciCgpwaGFzZSAiRXh0cmFjdGluZyAnJHtQQVJBTVNfREVTVElOQVRJT05fSU1BR0VfVVJMfScgZGVzdGluYXRpb24gaW1hZ2UgZGlnZXN0IgpkZXN0aW5hdGlvbl9kaWdlc3Q9IiQoc2tvcGVvX2luc3BlY3QgIiR7UEFSQU1TX0RFU1RJTkFUSU9OX0lNQUdFX1VSTH0iICIke1BBUkFNU19ERVNUX1RMU19WRVJJRll9IikiCnBoYXNlICJEZXN0aW5hdGlvbiBpbWFnZSBkaWdlc3QgJyR7ZGVzdGluYXRpb25fZGlnZXN0fSciCgpwcmludGYgIiVzIiAiJHtzb3VyY2VfZGlnZXN0fSIgPiAiJHtSRVNVTFRTX1NPVVJDRV9ESUdFU1RfUEFUSH0iCnByaW50ZiAiJXMiICIke2Rlc3RpbmF0aW9uX2RpZ2VzdH0iID4gIiR7UkVTVUxUU19ERVNUSU5BVElPTl9ESUdFU1RfUEFUSH0iCg==" |base64 -d >"/scripts/skopeo-results.sh"
        ls /scripts/skopeo-*.sh;
        chmod +x /scripts/skopeo-*.sh;echo "Running Script /scripts/skopeo-copy.sh";
          /scripts/skopeo-copy.sh;echo "Running Script /scripts/skopeo-results.sh";
          /scripts/skopeo-results.sh;
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
