---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/source: "https://github.com/openshift-virtualization/openshift-virtualization-pipelines-tasks"
    tekton.dev/deprecated: "true"
    tekton.dev/pipelines.minVersion: "0.43.0"
    tekton.dev/categories: Automation
    tekton.dev/tags: kubevirt
    tekton.dev/displayName: "OpenShift Virtualization copy template"
    tekton.dev/platforms: "linux/amd64"
    artifacthub.io/maintainers: |
      - name: KubeVirt Tekton tasks maintainers
        email: kubevirt-tekton-tasks@redhat.com
    artifacthub.io/provider: Red Hat
    artifacthub.io/recommendations: |
      - url: https://kubevirt.io/
    artifacthub.io/category: integration-delivery
  labels:
    app.kubernetes.io/version: v4.15.2
  name: copy-template
spec:
  description: >-
    Automates the copying of OpenShift template. The task copies original template 
    and saves it under new name or if parameter allowReplace is true, then it replaces 
    template with the same name.
  params:
    - name: sourceTemplateName
      description: Name of an OpenShift template to copy template from.
      type: string
    - name: sourceTemplateNamespace
      description: Namespace of an source OpenShift template to copy template from. (defaults to active namespace)
      type: string
      default: ""
    - name: targetTemplateName
      description: Name of an target OpenShift template.
      type: string
      default: ""
    - name: targetTemplateNamespace
      description: Namespace of an target OpenShift template to create in. (defaults to active namespace)
      type: string
      default: ""
    - name: allowReplace
      description: Allow replacing already existing template (same combination name/namespace). Allowed values true/false
      type: string
      default: "false"
  results:
    - name: name
      description: The name of a template that was created.
    - name: namespace
      description: The namespace of a template that was created.
  steps:
    - name: copytemplate
      image: "registry.redhat.io/container-native-virtualization/kubevirt-tekton-tasks-create-datavolume-rhel9:v4.15.2"
      command:
        - copy-template
      args:
        - "--output=yaml"
      env:
        - name: SOURCE_TEMPLATE_NAME
          value: $(params.sourceTemplateName)
        - name: SOURCE_TEMPLATE_NAMESPACE
          value: $(params.sourceTemplateNamespace)
        - name: TARGET_TEMPLATE_NAME
          value: $(params.targetTemplateName)
        - name: TARGET_TEMPLATE_NAMESPACE
          value: $(params.targetTemplateNamespace)
        - name: ALLOW_REPLACE
          value: $(params.allowReplace)
