---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rhacs-image-check
  labels:
    app.kubernetes.io/version: "3.73"
  annotations:
    tekton.dev/tags: security
    tekton.dev/categories: Security
    tekton.dev/displayName: "Policy check an image with Red Hat Advanced Cluster Security"
    tekton.dev/platforms: "linux/amd64"
    tekton.dev/pipelines.minVersion: "0.18.0"
spec:
  description: >-
    Policy check an image with Red Hat Advanced Cluster Security.

    This tasks allows you to check an image against build-time policies
    and apply enforcement to fail builds.  It's a companion to the
    rhacs-image-scan task, which returns full vulnerability scan
    results for an image.
  params:
    - name: rox_central_endpoint
      type: string
      description: Name of secret containing the address:port tuple for RHACS Stackrox Central.
      default: rox-central-endpoint
    - name: rox_api_token
      type: string
      description: Name of secret containing the RHACS StackRox API token with CI permissions.
      default: rox-api-token
    - name: rox_image
      description: Image providing the roxctl tool.
      default: quay.io/stackrox-io/roxctl:3.73.0
    - name: image
      type: string
      description: |
        Full name of image to check.
        Examples: 'gcr.io/rox/sample:5.0-rc1', '$(params.IMAGE)', '$(params.IMAGE)@$(tasks.buildah.results.IMAGE_DIGEST)'
      default: '$(params.IMAGE)'
    - name: output_format
      description: Results output format (csv | json | junit | table)
      type: string
      default: "table"
    - name: insecure-skip-tls-verify
      type: string
      description: |
        Do not verify TLS certificates.

        When set to "true", skip verifying the TLS certs of the Central endpoint and registry.
      default: "false"
  results:
    - name: check_output
      description: Output of `roxctl image check`
  steps:
    - name: rox-image-check
      image: $(params.rox_image)
      env:
        - name: HOME
          value: /tekton/home
        - name: IMAGE
          value: $(params.image)
        - name: INSECURE
          value: $(params.insecure-skip-tls-verify)
        - name: OUTPUT
          value: $(params.output_format)
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.rox_api_token)
              key: rox_api_token
        - name: ROX_CENTRAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: $(params.rox_central_endpoint)
              key: rox_central_endpoint
      args:
        - image
        - check
        - --endpoint=$(ROX_CENTRAL_ENDPOINT)
        - --insecure-skip-tls-verify=$(INSECURE)
        - --output=$(OUTPUT)
        - --image=$(IMAGE)