---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rox-api-token
data:
  rox_api_token: EXAMPLE
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  rox_central_endpoint: Y2VudHJhbC5zdGFja3JveC5zdmM6NDQz
metadata:
  name: rox-central-endpoint
