---
# Source: task-maven/templates/task-maven.yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: 0.3.1
  annotations:
    tekton.dev/source: "https://github.com/openshift-pipelines/task-maven"
    artifacthub.io/category: integration-delivery
    artifacthub.io/maintainers: |
      - name: OpenShift Pipeline task maintainers
        email: pipelines-extcomm@redhat.com
    artifacthub.io/provider: Red Hat
    artifacthub.io/recommendations: |
      - url: https://tekton.dev/
    tekton.dev/categories: containers
    tekton.dev/pipelines.minVersion: 0.41.0
    tekton.dev/tags: containers
spec:
  description: >-
    This Task can be used to run a Maven build.

  workspaces:
    - name: source
      optional: false
      description: The workspace consisting of maven project.
    - name: server_secret
      optional: true
      description: The workspace containing server secrets (username and password)
    - name: proxy_secret
      optional: true
      description: The workspace containing proxy server access credentials (username, password).
    - name: proxy_configmap
      optional: true
      description: The workspace containing some proxy values (proxy_port,proxy_host,proxy_protocol,proxy_non_proxy_hosts)
    - name: maven_settings
      optional: true
      description: The workspace consisting of the custom maven settings provided by the user.
  params:
    - name: GOALS
      description: maven goals to run
      type: array
      default:
        - "package"
    - name: MAVEN_MIRROR_URL
      description: The Maven repository mirror url
      type: string
      default: ""
    - name: SUBDIRECTORY
      type: string
      description: >-
        The subdirectory within the repository for sources on
        which we want to execute maven goals.
      default: "."

  stepTemplate:
    env:
      
      - name: PARAMS_MAVEN_MIRROR_URL
        value: "$(params.MAVEN_MIRROR_URL)"
      - name: PARAMS_SUBDIRECTORY
        value: "$(params.SUBDIRECTORY)"
      - name: WORKSPACES_SOURCE_PATH
        value: "$(workspaces.source.path)"
      - name: WORKSPACES_SOURCE_BOUND
        value: "$(workspaces.source.bound)"
      - name: WORKSPACES_SERVER_SECRET_PATH
        value: "$(workspaces.server_secret.path)"
      - name: WORKSPACES_SERVER_SECRET_BOUND
        value: "$(workspaces.server_secret.bound)"
      - name: WORKSPACES_PROXY_SECRET_PATH
        value: "$(workspaces.proxy_secret.path)"
      - name: WORKSPACES_PROXY_SECRET_BOUND
        value: "$(workspaces.proxy_secret.bound)"
      - name: WORKSPACES_PROXY_CONFIGMAP_PATH
        value: "$(workspaces.proxy_configmap.path)"
      - name: WORKSPACES_PROXY_CONFIGMAP_BOUND
        value: "$(workspaces.proxy_configmap.bound)"
      - name: WORKSPACES_MAVEN_SETTINGS_PATH
        value: "$(workspaces.maven_settings.path)"
      - name: WORKSPACES_MAVEN_SETTINGS_BOUND
        value: "$(workspaces.maven_settings.bound)"

  steps:
    - name: maven-generate
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.9
      env:
        - name: HOME
          value: /tekton/home
      script: |
        set -e
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKZGVjbGFyZSAtcnggTUFWRU5fR0VORVJBVEVfRElSRUNUT1JZPSIke1dPUktTUEFDRVNfU09VUkNFX1BBVEh9L21hdmVuLWdlbmVyYXRlIgoKZGVjbGFyZSAtcnggTUFWRU5fU0VUVElOR1NfRklMRT0iJHtNQVZFTl9HRU5FUkFURV9ESVJFQ1RPUll9L3NldHRpbmdzLnhtbCIKCmlmIFtbIC1mICR7TUFWRU5fU0VUVElOR1NfRklMRX0gXV07IHRoZW4KICAgIGVjaG8gInVzaW5nIGV4aXN0aW5nICcke01BVkVOX1NFVFRJTkdTX0ZJTEV9JyIKICAgIGNhdCAke01BVkVOX1NFVFRJTkdTX0ZJTEV9CiAgICBleGl0IDAKZmkKCiMgQ2hlY2sgaWYgc2V0dGluZ3MueG1sIGV4aXN0cyBpbiB0aGUgd29ya3NwYWNlIG1hdmVuLXNldHRpbmdzCmlmIFtbIC1mICIke1dPUktTUEFDRVNfTUFWRU5fU0VUVElOR1NfUEFUSH0vc2V0dGluZ3MueG1sIiBdXTsgdGhlbgogICAgY3AgIiR7V09SS1NQQUNFU19NQVZFTl9TRVRUSU5HU19QQVRIfS9zZXR0aW5ncy54bWwiICIke01BVkVOX1NFVFRJTkdTX0ZJTEV9IgogICAgZWNobyAiVXNpbmcgJyR7TUFWRU5fU0VUVElOR1NfRklMRX0nIGNvcGllZCBmcm9tIG9wdGlvbmFsIHdvcmtzcGFjZSBtYXZlbi1zZXR0aW5ncyIKICAgIGNhdCAke01BVkVOX1NFVFRJTkdTX0ZJTEV9CiAgICBleGl0IDAKZmkKCgpta2RpciAiJHtNQVZFTl9HRU5FUkFURV9ESVJFQ1RPUll9IgoKY2F0ID4gIiR7TUFWRU5fU0VUVElOR1NfRklMRX0iIDw8RU9GCjxzZXR0aW5ncz4KICAgIDxzZXJ2ZXJzPgogICAgPCEtLSBUaGUgc2VydmVycyBhZGRlZCBoZXJlIGFyZSBnZW5lcmF0ZWQgZnJvbSBlbnZpcm9ubWVudCB2YXJpYWJsZXMuIERvbid0IGNoYW5nZS4gLS0+CiAgICA8IS0tICMjIyBTRVJWRVIncyBVU0VSIElORk8gZnJvbSBFTlYgIyMjIC0tPgogICAgPC9zZXJ2ZXJzPgogICAgPG1pcnJvcnM+CiAgICA8IS0tIFRoZSBtaXJyb3JzIGFkZGVkIGhlcmUgYXJlIGdlbmVyYXRlZCBmcm9tIGVudmlyb25tZW50IHZhcmlhYmxlcy4gRG9uJ3QgY2hhbmdlLiAtLT4KICAgIDwhLS0gIyMjIG1pcnJvcnMgZnJvbSBFTlYgIyMjIC0tPgogICAgPC9taXJyb3JzPgogICAgPHByb3hpZXM+CiAgICA8IS0tIFRoZSBwcm94aWVzIGFkZGVkIGhlcmUgYXJlIGdlbmVyYXRlZCBmcm9tIGVudmlyb25tZW50IHZhcmlhYmxlcy4gRG9uJ3QgY2hhbmdlLiAtLT4KICAgIDwhLS0gIyMjIEhUVFAgcHJveHkgZnJvbSBFTlYgIyMjIC0tPgogICAgPC9wcm94aWVzPgo8L3NldHRpbmdzPgpFT0YKCmNhdCAiJHtNQVZFTl9TRVRUSU5HU19GSUxFfSIKCnhtbD0iIgppZiBbWyAiJHtXT1JLU1BBQ0VTX1BST1hZX1NFQ1JFVF9CT1VORH0iID09ICJ0cnVlIiBdXTsgdGhlbgogICAgaWYgdGVzdCAtZiAke1dPUktTUEFDRVNfUFJPWFlfU0VDUkVUX1BBVEh9L3VzZXJuYW1lICYmIHRlc3QgLWYgJHtXT1JLU1BBQ0VTX1BST1hZX1NFQ1JFVF9QQVRIfS9wYXNzd29yZDsgdGhlbgogICAgUEFSQU1TX1BST1hZX1VTRVI9JChjYXQgJHtXT1JLU1BBQ0VTX1BST1hZX1NFQ1JFVF9QQVRIfS91c2VybmFtZSkKICAgIFBBUkFNU19QUk9YWV9QQVNTV09SRD0kKGNhdCAke1dPUktTUEFDRVNfUFJPWFlfU0VDUkVUX1BBVEh9L3Bhc3N3b3JkKQoKICAgICMgRmV0Y2hpbmcgcHJveHkgY29uZmlndXJhdGlvbiB2YWx1ZXMgZnJvbSBDb25maWdNYXAgd29ya3NwYWNlCiAgICBQQVJBTVNfUFJPWFlfSE9TVD0kKGNhdCAke1dPUktTUEFDRVNfUFJPWFlfQ09ORklHTUFQX1BBVEh9L3Byb3h5X2hvc3QpCiAgICBQQVJBTVNfUFJPWFlfUE9SVD0kKGNhdCAke1dPUktTUEFDRVNfUFJPWFlfQ09ORklHTUFQX1BBVEh9L3Byb3h5X3BvcnQpCiAgICBQQVJBTVNfUFJPWFlfUFJPVE9DT0w9JChjYXQgJHtXT1JLU1BBQ0VTX1BST1hZX0NPTkZJR01BUF9QQVRIfS9wcm94eV9wcm90b2NvbCkKICAgIFBBUkFNU19QUk9YWV9OT05fUFJPWFlfSE9TVFM9JChjYXQgJHtXT1JLU1BBQ0VTX1BST1hZX0NPTkZJR01BUF9QQVRIfS9wcm94eV9ub25fcHJveHlfaG9zdHMpCgogICAgaWYgWyAtbiAiJHtQQVJBTVNfUFJPWFlfSE9TVH0iIC1hIC1uICIke1BBUkFNU19QUk9YWV9QT1JUfSIgXTsgdGhlbgogICAgICAgIHhtbD0iPHByb3h5PlwKICAgICAgICA8aWQ+Z2VucHJveHk8L2lkPlwKICAgICAgICA8YWN0aXZlPnRydWU8L2FjdGl2ZT5cCiAgICAgICAgPHByb3RvY29sPiR7UEFSQU1TX1BST1hZX1BST1RPQ09MfTwvcHJvdG9jb2w+XAogICAgICAgIDxob3N0PiR7UEFSQU1TX1BST1hZX0hPU1R9PC9ob3N0PlwKICAgICAgICA8cG9ydD4ke1BBUkFNU19QUk9YWV9QT1JUfTwvcG9ydD4iCiAgICAgICAgaWYgWyAtbiAiJHtQQVJBTVNfUFJPWFlfVVNFUn0iIC1hIC1uICIke1BBUkFNU19QUk9YWV9QQVNTV09SRH0iIF07IHRoZW4KICAgICAgICAgICAgeG1sPSIkeG1sXAogICAgICAgICAgICA8dXNlcm5hbWU+JHtQQVJBTVNfUFJPWFlfVVNFUn08L3VzZXJuYW1lPlwKICAgICAgICAgICAgPHBhc3N3b3JkPiR7UEFSQU1TX1BST1hZX1BBU1NXT1JEfTwvcGFzc3dvcmQ+IgogICAgICAgIGZpCiAgICAgICAgaWYgWyAtbiAiJHtQQVJBTVNfUFJPWFlfTk9OX1BST1hZX0hPU1RTfSIgXTsgdGhlbgogICAgICAgICAgICB4bWw9IiR4bWxcCiAgICAgICAgICAgIDxub25Qcm94eUhvc3RzPiR7UEFSQU1TX1BST1hZX05PTl9QUk9YWV9IT1NUU308L25vblByb3h5SG9zdHM+IgogICAgICAgIGZpCiAgICAgICAgeG1sPSIkeG1sXAogICAgICAgIDwvcHJveHk+IgogICAgICAgIHNlZCAtaSAic3w8IS0tICMjIyBIVFRQIHByb3h5IGZyb20gRU5WICMjIyAtLT58JHhtbHwiICR7TUFWRU5fU0VUVElOR1NfRklMRX0KICAgIGZpCiAgICBlbHNlCiAgICAgICAgZWNobyAibm8gJ3VzZXJuYW1lJyBvciAncGFzc3dvcmQnIGZpbGUgZm91bmQgYXQgd29ya3NwYWNlIHByb3h5X3NlY3JldCIKICAgICAgICBleGl0IDEKICAgIGZpCmZpCgppZiBbWyAiJHtXT1JLU1BBQ0VTX1NFUlZFUl9TRUNSRVRfQk9VTkR9IiA9PSAidHJ1ZSIgXV07IHRoZW4KICAgIGlmIHRlc3QgLWYgJHtXT1JLU1BBQ0VTX1NFUlZFUl9TRUNSRVRfUEFUSH0vdXNlcm5hbWUgJiYgdGVzdCAtZiR7V09SS1NQQUNFU19TRVJWRVJfU0VDUkVUX1BBVEh9L3Bhc3N3b3JkOyB0aGVuCglTRVJWRVJfVVNFUj0kKGNhdCAke1dPUktTUEFDRVNfU0VSVkVSX1NFQ1JFVF9QQVRIfS91c2VybmFtZSkKCVNFUlZFUl9QQVNTV09SRD0kKGNhdCAke1dPUktTUEFDRVNfU0VSVkVSX1NFQ1JFVF9QQVRIfS9wYXNzd29yZCkKCWlmIFsgLW4gIiR7U0VSVkVSX1VTRVJ9IiAtYSAtbiAiJHtTRVJWRVJfUEFTU1dPUkR9IiBdOyB0aGVuCgkgICAgeG1sPSI8c2VydmVyPlwKICAgICAgICA8aWQ+c2VydmVyaWQ8L2lkPiIKCSAgICB4bWw9IiR4bWxcCiAgICAgICAgPHVzZXJuYW1lPiR7U0VSVkVSX1VTRVJ9PC91c2VybmFtZT5cCiAgICAgICAgPHBhc3N3b3JkPiR7U0VSVkVSX1BBU1NXT1JEfTwvcGFzc3dvcmQ+IgoJICAgIHhtbD0iJHhtbFwKICAgICAgICA8L3NlcnZlcj4iCgkgICAgc2VkIC1pICJzfDwhLS0gIyMjIFNFUlZFUidzIFVTRVIgSU5GTyBmcm9tIEVOViAjIyMgLS0+fCR4bWx8IiAke01BVkVOX1NFVFRJTkdTX0ZJTEV9CgkgICAgZWNobyAiU0VSVkVSIENyZWRzIFVwZGF0ZWQiCglmaQogICAgZWxzZQoJZWNobyAibm8gJ3VzZXInIG9yICdwYXNzd29yZCcgZmlsZSBmb3VuZCBhdCB3b3Jrc3BhY2Ugc2VydmVyX3NlY3JldCIKICAgICAgICBleGl0IDEKICAgIGZpCmZpCgppZiBbIC1uICIke1BBUkFNU19NQVZFTl9NSVJST1JfVVJMfSIgXTsgdGhlbgogICAgeG1sPSIgICAgPG1pcnJvcj5cCiAgICA8aWQ+bWlycm9yLmRlZmF1bHQ8L2lkPlwKICAgIDx1cmw+JHtQQVJBTVNfTUFWRU5fTUlSUk9SX1VSTH08L3VybD5cCiAgICA8bWlycm9yT2Y+Y2VudHJhbDwvbWlycm9yT2Y+XAogICAgPC9taXJyb3I+IgogICAgc2VkIC1pICJzfDwhLS0gIyMjIG1pcnJvcnMgZnJvbSBFTlYgIyMjIC0tPnwkeG1sfCIgJHtNQVZFTl9TRVRUSU5HU19GSUxFfQpmaQo=" |base64 -d >"/scripts/maven-generate.sh"
        ls /scripts/maven-*.sh;
        chmod +x /scripts/maven-*.sh;echo "Running Script /scripts/maven-generate.sh";
          /scripts/maven-generate.sh;
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
        - name: maven-settings-dir
          mountPath: /maven-generate

    - name: maven-goals
      env:
        - name: HOME
          value: /tekton/home
      image: registry.access.redhat.com/ubi8/openjdk-11:latest
      workingDir: $(workspaces.source.path)/$(params.SUBDIRECTORY)
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - maven-generate/settings.xml
        - "$(params.GOALS[*])"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: maven-settings-dir
          mountPath: /maven-generate

  volumes:
    - name: scripts-dir
      emptyDir: {}
    - name: maven-settings-dir
      emptyDir: {}
